version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: codecraft
    volumes:
      - ./database:/docker-entrypoint-initdb.d
